import React from 'react'
import Head from 'next/head'

import { useEffect, useState } from 'react'

import Loading from '../components/shared/Loading'
import Card from '../components/Card'

//hooks
import { Auth } from 'hooks/apiCms'

interface UserValue  {
  id: string;
  role: string;
  username: string;
  password: string;
}

export default function Index() {

  const [ user, setUser ] = useState<UserValue[]>([])
  const [ isLoading, setLoading ] = useState(true)

  const useSingle = async () => {
    useEffect(() => {
      setTimeout(async () => {

        async function teste() {

          const {response, result} = await Auth()

          if(response.status === 200) {
            window.localStorage.setItem('user', JSON.stringify(result))
            setUser(JSON.parse(window.localStorage.user))
            setLoading(false)
          }

          if(response.status !== 200) {
            setTimeout( async () => {
              await teste()
            }, 1000)
          }
        }

        await teste()


      }, 1000)
    }, [])
  }

  useSingle()



  return (
    <div className="container">
      <Head>
      <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{width: '100vw', height: '100vh', justifyContent: 'center', alignItems: 'center'}}>
        { isLoading && <Loading /> }
        { user.username && <Card username={user.username} /> }
      </div>

    </div>
  )
}
